
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utxgyiitfmbzqwkncckb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0eGd5aWl0Zm1ienF3a25jY2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDA4MjgsImV4cCI6MjA2MzQ3NjgyOH0.GCNqWtl0PEoIAzQk21h5rXH1iMwP-Yo330LKcPtj6zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
